### ISSUE TITLE
user.logout failed 

### ISSUE THREAD

**Issue by bymzy** [jesuslosada/zabbix-client#3]
zabbix 4.0

according to the docs 
[https://www.zabbix.com/documentation/4.0/manual/api/reference/user/logout](url)

`{
    "jsonrpc": "2.0",
    "method": "user.logout",
    "params": [],
    "id": 1,
    "auth": "16a46baf181ef9602e1687f3110abf8a"
}`

i think that "params" is missed when calling user.logout

**Comment by jesuslosada** [comment]
Hi @bymzy . Thanks for the report! It looks like this changed in Zabbix 3. It's a bit weird because the JSON-RPC specification says `params` can be omitted, but Zabbix seems to require it anyway. I've only found a vague reference to this issue: https://support.zabbix.com/browse/ZBX-9700
I've released a new version (0.1.2) that should fix this issue.
